"""Core domain layer: identity, parsers, and business rules."""

from .identity import (
    infer_process_class_from_number,
    normalize_entity_name,
    normalize_process_code,
    stable_id,
)
from .parsers import (
    as_optional_str,
    counsel_entries_from_juris_partes,
    first_non_null,
    infer_process_number,
    is_missing,
    parse_bool_collegiate,
    parse_decision_year,
    party_entries_from_juris_partes,
    split_name_list,
    split_party_names,
    split_subjects,
)
from .rules import (
    FAVORABLE_OUTCOMES,
    NEUTRAL_OUTCOMES,
    RULE_VERSION,
    UNFAVORABLE_OUTCOMES,
    GroupKey,
    classify_group_size,
    classify_outcome_for_party,
    classify_outcome_raw,
    derive_thematic_key,
)
from .stats import (
    autocorrelation_lag1,
    chi_square_p_value_approx,
    chi_square_statistic,
    odds_ratio,
    z_score,
)

__all__ = [
    "FAVORABLE_OUTCOMES",
    "GroupKey",
    "NEUTRAL_OUTCOMES",
    "RULE_VERSION",
    "UNFAVORABLE_OUTCOMES",
    "classify_outcome_for_party",
    "classify_outcome_raw",
    "autocorrelation_lag1",
    "chi_square_p_value_approx",
    "chi_square_statistic",
    "as_optional_str",
    "classify_group_size",
    "counsel_entries_from_juris_partes",
    "derive_thematic_key",
    "first_non_null",
    "infer_process_class_from_number",
    "infer_process_number",
    "is_missing",
    "normalize_entity_name",
    "normalize_process_code",
    "odds_ratio",
    "parse_bool_collegiate",
    "parse_decision_year",
    "party_entries_from_juris_partes",
    "split_name_list",
    "split_party_names",
    "split_subjects",
    "stable_id",
    "z_score",
]
