"""TPU (Tabelas Processuais Unificadas) normalization layer.

Reads static JSON artifacts from ``data/reference/`` generated by
``scripts/build_tpu_tables.py`` from official SGT/CNJ tables.

All public functions are pure (no I/O after module load).
"""

from __future__ import annotations

import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_REFERENCE_DIR = Path("data/reference")

# ---------------------------------------------------------------------------
# Lazy loading of reference data
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _load_reference(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> dict[str, Any]:
    """Load all TPU reference files once and cache the result."""
    classes: dict[str, str] = {}
    movements: dict[str, str] = {}
    subjects: dict[str, str] = {}
    version: dict[str, Any] = {}

    classes_path = reference_dir / "tpu_classes.json"
    movements_path = reference_dir / "tpu_movements.json"
    subjects_path = reference_dir / "tpu_subjects.json"
    version_path = reference_dir / "tpu_version.json"

    if classes_path.exists():
        classes = json.loads(classes_path.read_text(encoding="utf-8"))
    else:
        logger.warning("TPU classes file not found: %s", classes_path)

    if movements_path.exists():
        movements = json.loads(movements_path.read_text(encoding="utf-8"))
    else:
        logger.warning("TPU movements file not found: %s", movements_path)

    if subjects_path.exists():
        subjects = json.loads(subjects_path.read_text(encoding="utf-8"))
    else:
        logger.warning("TPU subjects file not found: %s", subjects_path)

    if version_path.exists():
        version = json.loads(version_path.read_text(encoding="utf-8"))

    return {
        "classes": classes,
        "movements": movements,
        "subjects": subjects,
        "version": version,
    }


def _classes(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> dict[str, str]:
    return _load_reference(reference_dir)["classes"]


def _movements(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> dict[str, str]:
    return _load_reference(reference_dir)["movements"]


def _subjects(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> dict[str, str]:
    return _load_reference(reference_dir)["subjects"]


def tpu_version(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> str:
    """Return the TPU version string from the reference data."""
    ver = _load_reference(reference_dir)["version"]
    return str(ver.get("sgt_version", "unknown"))


# ---------------------------------------------------------------------------
# Movement category classification
# ---------------------------------------------------------------------------

# Semantic families for movement categories, keyed by keywords in the
# movement description (Portuguese).  Order matters: first match wins.
_CATEGORY_PATTERNS: list[tuple[str, list[str]]] = [
    # Order matters: more specific patterns MUST come before general ones.
    # "redistribu" before "distribuí"; "trânsito em julgado" before "julgado".
    ("deslocamento", [
        "deslocamento", "redistribu", "remessa", "remessa a",
        "remetido", "encaminhado", "prevenção", "prevencao",
    ]),
    ("baixa", [
        "baixa", "trânsito em julgado", "transito em julgado",
        "arquivado", "arquivamento",
    ]),
    ("distribuicao", [
        "distribuí", "distribui", "sorteio", "sorteado",
        "distribuição", "distribuido",
    ]),
    ("vista", [
        "vista", "devolvidos autos",
    ]),
    ("pauta", [
        "pauta", "incluído em pauta", "retirado de pauta",
        "incluido em pauta", "retirada de pauta",
    ]),
    ("recurso", [
        "embargos", "agravo", "recurso",
    ]),
    ("decisao", [
        "julgamento", "julgado", "decisão", "decisao",
        "provido", "provimento", "improvido", "negado",
        "deferido", "indeferido", "procedente", "improcedente",
        "concedido", "prejudicado", "extinto",
    ]),
    ("publicacao", [
        "publicação", "publicacao", "publicado", "diário", "diario",
        "intimação", "intimacao",
    ]),
]


def categorize_movement_text(description: str | None) -> str:
    """Classify a raw movement description into a semantic category.

    Returns one of: distribuicao, vista, pauta, decisao, recurso,
    publicacao, deslocamento, baixa, outros.
    """
    if not description:
        return "outros"
    desc_lower = description.lower()
    for category, keywords in _CATEGORY_PATTERNS:
        for keyword in keywords:
            if keyword in desc_lower:
                return category
    return "outros"


# ---------------------------------------------------------------------------
# Semantic boolean classifiers
# ---------------------------------------------------------------------------

_REDISTRIBUTION_KEYWORDS = frozenset({
    "redistribu", "redistribuição", "redistribuicao",
    "redistribuído", "redistribuido",
})

_VISTA_KEYWORDS = frozenset({
    "pedido de vista", "vista dos autos", "vista ao",
})

_DEVOLVIDO_VISTA_KEYWORDS = frozenset({
    "devolvidos autos", "devolução de vista", "devolvido vista",
    "devolvidos os autos", "devolucao de vista",
})

_PAUTA_INCLUSION_KEYWORDS = frozenset({
    "incluído em pauta", "incluido em pauta",
    "incluída em pauta", "incluida em pauta",
    "inclusão em pauta", "inclusao em pauta",
})

_PAUTA_WITHDRAWAL_KEYWORDS = frozenset({
    "retirado de pauta", "retirada de pauta",
    "retirado da pauta", "retirada da pauta",
    "exclusão de pauta", "exclusao de pauta",
})

_PREVENCAO_KEYWORDS = frozenset({
    "prevenção", "prevencao", "prevento", "prevenido",
})


def _matches_any(text_lower: str, keywords: frozenset[str]) -> bool:
    return any(kw in text_lower for kw in keywords)


def is_redistribution(description: str | None) -> bool:
    """Check if movement description indicates rapporteur redistribution."""
    if not description:
        return False
    return _matches_any(description.lower(), _REDISTRIBUTION_KEYWORDS)


def is_pedido_de_vista(description: str | None) -> bool:
    """Check if movement description indicates a request for review (vista)."""
    if not description:
        return False
    return _matches_any(description.lower(), _VISTA_KEYWORDS)


def is_devolvido_vista(description: str | None) -> bool:
    """Check if movement description indicates return from vista."""
    if not description:
        return False
    return _matches_any(description.lower(), _DEVOLVIDO_VISTA_KEYWORDS)


def is_pauta_inclusion(description: str | None) -> bool:
    """Check if movement description indicates inclusion in session agenda."""
    if not description:
        return False
    return _matches_any(description.lower(), _PAUTA_INCLUSION_KEYWORDS)


def is_pauta_withdrawal(description: str | None) -> bool:
    """Check if movement description indicates removal from session agenda."""
    if not description:
        return False
    return _matches_any(description.lower(), _PAUTA_WITHDRAWAL_KEYWORDS)


def is_prevencao(description: str | None) -> bool:
    """Check if movement description indicates prevention/preemption."""
    if not description:
        return False
    return _matches_any(description.lower(), _PREVENCAO_KEYWORDS)


# ---------------------------------------------------------------------------
# TPU code lookup
# ---------------------------------------------------------------------------

def tpu_class_name(code: int, reference_dir: Path = DEFAULT_REFERENCE_DIR) -> str | None:
    """Return the official TPU class name for a numeric code, or None."""
    return _classes(reference_dir).get(str(code))


def tpu_movement_name(code: int, reference_dir: Path = DEFAULT_REFERENCE_DIR) -> str | None:
    """Return the official TPU movement name for a numeric code, or None."""
    return _movements(reference_dir).get(str(code))


def tpu_subject_name(code: int, reference_dir: Path = DEFAULT_REFERENCE_DIR) -> str | None:
    """Return the official TPU subject name for a numeric code, or None."""
    return _subjects(reference_dir).get(str(code))


# ---------------------------------------------------------------------------
# Sigla → TPU code resolution
# ---------------------------------------------------------------------------

# Common STF class abbreviations mapped to TPU codes.
# Populated from data/reference/tpu_classes.json via _build_sigla_index().
_SIGLA_CACHE: dict[str, int] | None = None


def _normalize_sigla(sigla: str) -> str:
    """Normalize a class abbreviation for lookup."""
    return re.sub(r"\s+", " ", sigla.strip().upper())


@lru_cache(maxsize=1)
def _build_sigla_index(reference_dir: Path = DEFAULT_REFERENCE_DIR) -> dict[str, int]:
    """Build a reverse index from class name/sigla to TPU code.

    Extracts the abbreviation from the beginning of the class name
    (e.g., 'ADI' from 'Ação Direta de Inconstitucionalidade')
    and also stores the full name for exact match.
    """
    index: dict[str, int] = {}
    for code_str, name in _classes(reference_dir).items():
        code = int(code_str)
        name_upper = name.upper()
        index[name_upper] = code

        # Common pattern: abbreviation is all-caps prefix or parenthesized
        # We also store the original code string mapping
        # This gets supplemented by manual STF abbreviation mapping below
    # Manual STF class abbreviations → TPU codes
    # These are the most common classes at the STF that may not be directly
    # derivable from TPU class names.
    # STF section in TPU (codes 1310-1384)
    _MANUAL_SIGLA: dict[str, int] = {
        "ADI": 1314,
        "ADPF": 1322,
        "ADC": 1313,
        "ADO": 12775,
        "RE": 1348,
        "ARE": 1045,
        "HC": 1331,
        "MS": 1336,
        "MI": 1335,
        "RCL": 1342,
        "AC": 1311,
        "ACO": 1315,
        "AO": 1312,
        "AP": 1317,
        "AS": 1323,
        "AI": 1320,
        "INQ": 1333,
        "IF": 1334,
        "EXT": 1330,
        "PET": 1338,
        "SE": 1350,
        "SS": 1353,
        "SL": 1352,
        "STA": 1354,
        "CR": 1324,
    }
    for sigla, code in _MANUAL_SIGLA.items():
        index[sigla] = code

    return index


def normalize_class_sigla_to_tpu(
    sigla: str, reference_dir: Path = DEFAULT_REFERENCE_DIR,
) -> int | None:
    """Try to resolve a process class abbreviation to a TPU code.

    Returns the code if found, None otherwise.
    """
    key = _normalize_sigla(sigla)
    idx = _build_sigla_index(reference_dir)
    return idx.get(key)


# ---------------------------------------------------------------------------
# Movement code categorization (for TPU numeric codes)
# ---------------------------------------------------------------------------

# Mapping from TPU movement codes to semantic categories.
# Populated from the reference data; supplemented by manual mapping
# for the most common STF-relevant movement codes.
_MOVEMENT_CATEGORY_BY_CODE: dict[int, str] = {
    # Distribution family
    26: "distribuicao",
    12474: "distribuicao",
    # Redistribution / deslocamento family
    36: "deslocamento",
    12255: "deslocamento",  # Redistribuição por prevenção
    12646: "deslocamento",  # Determinada a Redistribuição
    # Decision family
    193: "decisao",
    12213: "decisao",  # Decisão Monocrática
    12199: "decisao",  # Julgado
    # Vista family
    12204: "vista",  # Pedido de Vista
    14091: "vista",  # Devolvidos os autos após Pedido de Vista
    12315: "vista",  # Devolvidos os autos
    # Pauta family
    417: "pauta",  # Inclusão em pauta
    12104: "pauta",  # Inclusão em pauta
    12105: "pauta",  # Inclusão em Pauta de Sessão Virtual
    897: "pauta",  # Retirada de pauta
    12309: "pauta",  # Retirada
    # Publication family
    92: "publicacao",  # Publicação
    1061: "publicacao",  # Disponibilização no DJe
    # Baixa family
    22: "baixa",  # Baixa Definitiva
    848: "baixa",  # Trânsito em julgado
    246: "baixa",  # Definitivo
    228: "baixa",  # Arquivamento
    861: "baixa",  # Arquivamento
}


def movement_category_by_code(tpu_code: int) -> str:
    """Return the semantic category for a TPU movement code.

    Falls back to 'outros' if the code is not mapped.
    """
    return _MOVEMENT_CATEGORY_BY_CODE.get(tpu_code, "outros")
